default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

development:
  <<: *default
  database: pets_development
test:
  <<: *default
  database: pets_test
production:
  <<: *default
  database: pets_production
  username: pets
  password: <%= ENV["PETS_DATABASE_PASSWORD"] %>




